### ISSUE TITLE
Make --output-text-file optional in scater-calculate-cpm.R

### ISSUE THREAD

**Issue by nh3** [ebi-gene-expression-group/bioconductor-scater-scripts#15]
Currently this option is mandatory. It writes cpm expression quantification in a dense matrix format as a text file, which is highly inefficient for storage for scRNA-seq quantification which is usually sparse, and causing long runtime due to IO. As the information is already in the output RDS object and method exists to output as sparse matrix, this option should be made optional.

**Comment by pinin4fjords** [comment]
Go for it - propose a PR :-)

**Comment by nh3** [comment]
Solved in commit 8772f9a03cb3b7bd79fad8cbf84afd93a3070646
